Закончить выполнение lab4 и выполнение code review
RodionGromo/bukep_internship_2023 pull request #1
Opened 2023-11-16 20:28 UTC by RodionGromo

# Изменения:
- `.gitignore` теперь шаблонный с репозитория [.NET](https://github.com/microsoft/dotnet/blob/main/.gitignore)
- Добавлена программа `BUKEP.Student.ConsoleTodo`

2023-11-17 07:04 UTC, DmitryKrekshin requested changes

2023-11-17 07:04 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.ConsoleTodo/Program.cs
> +                if (!string.IsNullOrEmpty(userin))
вместо IsNullOrEmpty, стоит использовать IsNullOrWhiteSpace, если интересны подробности, вот: https://stackoverflow.com/questions/18710644/difference-between-isnullorempty-and-isnullorwhitespace-in-c-sharp

2023-11-17 10:38 UTC, RodionGromo commented on student_223024/BUKEP.Student.ConsoleTodo/Program.cs
> +        struct Task
Отделил в Program.Task

2023-11-17 10:46 UTC, RodionGromo commented on student_223024/BUKEP.Student.ConsoleTodo/Program.cs
> +        static int GetUserInt(string? message=null, bool addnewline=true)
Изменил стиль параметров на camelCase, соглашение по оформлению прочитаю обязательно

2023-11-17 10:47 UTC, RodionGromo commented on student_223024/BUKEP.Student.ConsoleTodo/Program.cs
> +                if (!string.IsNullOrEmpty(userin))
Исправил на IsNullOrWhiteSpace

2023-11-17 10:50 UTC, RodionGromo commented on student_223024/BUKEP.Student.ConsoleTodo/Program.cs
> +                Console.WriteLine("Нет добавленных дел\n");
Действительно, упустил этот момент

2023-11-17 10:51 UTC, RodionGromo commented on student_223024/BUKEP.Student.ConsoleTodo/Program.cs
> +                if (!string.IsNullOrEmpty(userin))
исправил

2023-11-17 10:55 UTC, RodionGromo commented on student_223024/BUKEP.Student.ConsoleTodo/Program.cs
> +                } else {
Исправил стиль везде, где нашел

2023-11-17 11:00 UTC, RodionGromo commented on student_223024/BUKEP.Student.ConsoleTodo/Program.cs
> +            taskMenu_actions.Add("Выйти из программы");
Вот тут спорный момент, если вдруг мы захотим добавить удаление задачи, то индекс программы будет другой, а это вредно для функции `RequestQuit`, в которой подтверждение завязано на том что индекс выхода из программы другой

Да, можно заставить программу найти элемент в списке который подходит, но так будет проще

2023-11-17 11:00 UTC, RodionGromo commented on student_223024/BUKEP.Student.ConsoleTodo/Program.cs
> +            taskMenu_actions.Add("Выйти из программы");
Или от ТЗ лучше не отходить?)

2023-11-17 12:30 UTC, DmitryKrekshin requested changes

2023-11-17 12:30 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.ConsoleTodo/Program.cs
> +                // c code-review: стоит использовать string.IsNullOrWhiteSpace, т.к. она покрывает IsNullOrEmpty, и еще пару краевых случаев
нет необходимости в таком комментарии

2023-11-17 12:30 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.ConsoleTodo/Program.cs
> +            taskMenu_actions.Add("Выйти из программы");
Т.е. смысл в том, чтобы действие выхода всегда было в конце? Нам ничего не мешает всегда оставлять его в конце списка. Если захотим добавить операцию удаления, то просто добавим ее в список перед операцией выхода.

А в целом, проявляются минусы от использования списка, в качестве хранилища операций. Лучшим решением было бы использовать enum, примерно в таком виде:
_public enum EducationalForm
{
    ShowTasks = 1,
    AddTask = 2,
    Quit = 3
}_
такой подход будет более правильным, но повлечет за собой усложнение кода (скажем, чтобы в этом же перечислении хранить название операции, которое будет выводиться в консоль), поэтому я не настаиваю на переписывании)

2023-11-17 12:39 UTC, RodionGromo commented on student_223024/BUKEP.Student.ConsoleTodo/Program.Task.cs
> +    internal partial class Program
Точно, точно, я просто использовал вынос который предлагал Visual Studio, сам не догадался

2023-11-17 12:40 UTC, RodionGromo commented on student_223024/BUKEP.Student.ConsoleTodo/Program.Task.cs
> +        struct Task
Обязательно учту

2023-11-17 12:40 UTC, RodionGromo commented on student_223024/BUKEP.Student.ConsoleTodo/Program.cs
> +    internal partial class Program
есть

2023-11-17 12:41 UTC, RodionGromo commented on student_223024/BUKEP.Student.ConsoleTodo/Program.cs
> +                // c code-review: стоит использовать string.IsNullOrWhiteSpace, т.к. она покрывает IsNullOrEmpty, и еще пару краевых случаев
согласен, думаю я запомнил

2023-11-17 12:42 UTC, RodionGromo commented on student_223024/BUKEP.Student.ConsoleTodo/Program.cs
> +            taskMenu_actions.Add("Выйти из программы");
Это точно, я куда то не туда думал с этой темой

2023-11-17 12:50 UTC, DmitryKrekshin approved these changes
Оставил еще один небольшой коммент и одобрил вливание

2023-11-17 12:50 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.ConsoleTodo/Program.Task.cs
> +    struct Task
Имя файла, кстати тоже должно быть Task

2023-11-17 12:52 UTC, RodionGromo commented on student_223024/BUKEP.Student.ConsoleTodo/Program.Task.cs
> +    struct Task
Оу, хорошо, сейчас переименую

2023-11-20 18:33 UTC, SheinEA approved these changes

2023-11-20 18:37 UTC, merged