Завершение lab5, ревью кода
RodionGromo/bukep_internship_2023 pull request #2
Opened 2023-11-22 18:38 UTC by RodionGromo

# вкратце
Написал три окна, вывел класс задачи в другой файл, не уверен что имелось ввиду под 
> функциональность работы со списком задач должна быть определена в отдельном классе

ведь её почти нет, помимо 1-2 строчек в двух файлах дополнительных окон
## есть небольшой костыль
в WPF насколько я понимаю нет подсказки в TextBox, поэтому там стоит заготовленный текст, который удаляется как только на текстбоксе фокусируются

2023-11-22 18:40 UTC, RodionGromo commented on student_223024/BUKEP.Student.WindowsTodo/AddTaskWindow.xaml.cs
> +        private void RemoveTextTemplate_Name(object sender, RoutedEventArgs e)
вот эти следующие методы RemoveTextTemplate и AddTextTemplate и есть те самые костыли

2023-11-23 07:45 UTC, DiBez1115 requested changes

2023-11-23 07:45 UTC, DiBez1115 commented on student_223024/BUKEP.Student.WindowsTodo/RemoveModalWindow.xaml.cs
> +                throw new ArgumentException("sender is null");
Момент странный, ты выбрасываешь исключение, но в MainWindow на 26 строке нету try и catch. Протестируй и посмотри этот момент, просто из-за этого может валится проект. У меня не запускается проект, поэтому протестировать не могу :(

2023-11-23 07:45 UTC, DiBez1115 commented on student_223024/BUKEP.Student.WindowsTodo/TaskItem.cs
> +    public class TaskItem
Добавить описание класса, полей и конструктора. Хоть тут все и элементарно, но описание должно быть.

2023-11-23 07:54 UTC, DmitryKrekshin requested changes

2023-11-23 07:54 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.WindowsTodo/MainWindow.xaml.cs
> +            foreach (var item in TaskList)
вместо цикла попробуй это: TaskViewList.Items.Add(TaskList);

2023-11-23 07:54 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.WindowsTodo/TaskItem.cs
> +        public TaskItem(string name, string description)
Обычно для подобных классов не создают конструкторы. Т.к. в них могут быть десятки свойств и сложно каждое из них инициализировать через конструктор, да и невсегда нужно.
Объекты в таком случае создаются примерно так: var rast = new TaskItem { Name = "Name", Description = "Description" }

2023-11-23 07:54 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.WindowsTodo/RemoveModalWindow.xaml.cs
> +        public RemoveModal(object? sender)
лучше отказаться от передачи sender. Это сбивает с толку (создается ощущение, что это обработчки события, а не конструктор). Пусть конструктор принимает TaskItem.

2023-11-23 07:54 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.WindowsTodo/RemoveModalWindow.xaml.cs
> +        public RemoveModal(object? sender)
+ если не ошибаюсь в этой версии c#, если параметр без ?, то он не может быть передан как null, тогда необходимость в проверке ниже пропадет

2023-11-23 08:19 UTC, RodionGromo commented on student_223024/BUKEP.Student.WindowsTodo/RemoveModalWindow.xaml.cs
> +        public RemoveModal(object? sender)
Согласен, неудачное решение передавать sender, исправил на прием TaskItem

2023-11-23 08:20 UTC, RodionGromo commented on student_223024/BUKEP.Student.WindowsTodo/RemoveModalWindow.xaml.cs
> +                throw new ArgumentException("sender is null");
Тестил, из интерфейса ничего не вылетает

2023-11-23 08:21 UTC, RodionGromo commented on student_223024/BUKEP.Student.WindowsTodo/TaskItem.cs
> +    public class TaskItem
добавил описание, с конструктором пришлось расстаться

2023-11-23 08:21 UTC, RodionGromo commented on student_223024/BUKEP.Student.WindowsTodo/TaskItem.cs
> +        public TaskItem(string name, string description)
убрал конструктор

2023-11-23 08:21 UTC, RodionGromo commented on student_223024/BUKEP.Student.WindowsTodo/MainWindow.xaml.cs
> +        public List<TaskItem> TaskList = new()
справедливо

2023-11-23 08:27 UTC, RodionGromo commented
последний коммит еще нужно проверить, плюс еще кое-что дописать

2023-11-23 08:50 UTC, DiBez1115 commented on student_223024/BUKEP.Student.WindowsTodo/RemoveModalWindow.xaml.cs
> +                throw new ArgumentException("sender is null");
Не вылетает, но если он попадет в исключение, то все падает.

2023-11-23 16:50 UTC, RodionGromo commented on student_223024/BUKEP.Student.WindowsTodo/RemoveModalWindow.xaml.cs
> +        public RemoveModal(object? sender)
проверил, ничего не сломалось

2023-11-23 16:51 UTC, RodionGromo commented on student_223024/BUKEP.Student.WindowsTodo/RemoveModalWindow.xaml.cs
> +                throw new ArgumentException("sender is null");
в последующих коммитах от этого исключения избавился

2023-11-23 16:51 UTC, RodionGromo commented on student_223024/BUKEP.Student.WindowsTodo/TaskItem.cs
> +        public TaskItem(string name, string description)
проверил

2023-11-23 16:52 UTC, RodionGromo commented on student_223024/BUKEP.Student.WindowsTodo/AddTaskWindow.xaml.cs
> +        readonly string enterTitleTemplate = "Введите заголовок задачи...";
исправил везде где применимо

2023-11-24 06:06 UTC, DmitryKrekshin requested changes
Кстати, при прошлом просмотре я забыл про требование, вынесения логики в отдельный файл. Нужен отдельный класс, в нем будет логика добавления/получения/удаления задач.
Это нужно, чтобы допустим, если мы создадим другое приложение, скажем web, то мы могли бы скопировать логику.
Таким образом, логика будет отделена от UI

2023-11-24 06:06 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.WindowsTodo/TaskItem.cs
> +        public string? Name { get; set;}
Развае логика приложения подразумевает, что имя задачи может не заполняться? Если нет, то вопросик стоит убрать. Чтобы компилятор не ругался перед strign можно написать required.

2023-11-25 10:33 UTC, RodionGromo commented on student_223024/BUKEP.Student.WindowsTodo/AddTaskWindow.xaml.cs
> +            if(TaskNameInput.Text.Equals(enterTitleTemplate)) return;
так можно делать? я смотрел смотрел на соглашение по кодированию, но ничего такого не увидел

2023-11-25 10:54 UTC, RodionGromo commented
Я только что выяснил фичу `List.Contains` ([сравнение элементов происходит по ссылкам а не по значениям](https://stackoverflow.com/a/9725678/18749611)), и мне пришлось дописать функцию `ContainsTask` для запрета добавления одинаковых задач в список

2023-11-26 09:18 UTC, DmitryKrekshin approved these changes
Предложил еще несколько улучшений и одобрил 👍

2023-11-26 09:18 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.WindowsTodo/TaskManager.cs
> +        public bool ContainsTask(TaskItem task)
upd: можно вообще отказаться от этого метода.
Для проверки наличия задачи с указанным именем, можно использовать _TaskList.All(t => t.Name != item.Name)_.
Метод All проверяет, что все элементы в списке удовлетворяют переданному предикату

2023-11-26 09:18 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.WindowsTodo/AddTaskWindow.xaml.cs
> +            if(TaskNameInput.Text.Equals(enterTitleTemplate)) return;
Мы всегда пишем так:
if(TaskNameInput.Text.Equals(enterTitleTemplate))
{
    return;
}

2023-11-26 09:18 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.WindowsTodo/AddTaskWindow.xaml.cs
> +            MainWindow.taskMan.AddTask(TaskNameInput.Text, actualDescription);
Это, конечно, не верный подход. Нужно чтобы у каждой страницы был свой TaskManager, но это реализуется, при помощи внедрения зависимостей, поэтому на данный момент можно оставить так

2023-11-26 10:15 UTC, RodionGromo commented on student_223024/BUKEP.Student.WindowsTodo/AddTaskWindow.xaml.cs
> +            if(TaskNameInput.Text.Equals(enterTitleTemplate)) return;
запомнил, исправил

2023-11-26 10:29 UTC, RodionGromo commented on student_223024/BUKEP.Student.WindowsTodo/TaskManager.cs
> +        public void AddTask(TaskItem item)
понял, убрал лишние перегрузки

2023-11-26 10:30 UTC, RodionGromo commented on student_223024/BUKEP.Student.WindowsTodo/AddTaskWindow.xaml.cs
> +            MainWindow.taskMan.AddTask(TaskNameInput.Text, actualDescription);
немного поискал насчет внедрения зависимости, в следующий раз попробую внедрить

2023-11-26 10:39 UTC, RodionGromo commented on student_223024/BUKEP.Student.WindowsTodo/TaskManager.cs
> +        public bool ContainsTask(TaskItem task)
ну да, можно и отказаться, но тогда либо предикат делать сложный с расчетом на null описание, либо мириться с тем что могут быть две одинаковые задачи с разными описаниями

на данный момент просто сделал функцию приватной

2023-11-26 11:25 UTC, DiBez1115 approved these changes

2023-11-26 19:48 UTC, SheinEA approved these changes

2023-11-26 19:50 UTC, merged