завершение lab8, ревью кода
RodionGromo/bukep_internship_2023 pull request #8
Opened 2023-12-27 17:31 UTC by RodionGromo

ээх потерял пошаговые коммиты, но думаю наконец-то запомню что нужно из main делать новые ветки а не из прошлых веток

2023-12-28 16:48 UTC, DmitryKrekshin requested changes

2023-12-28 16:48 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.Todo.Data/BUKEP.Student.Todo.Data.csproj
> +    <ProjectReference Include="..\BUKEP.Student.Todo\BUKEP.Student.Todo.csproj" />
Правильнее было бы вынести ITaskManager и Task в отдельную библиотеку и ее уже подключать к Student.Todo и Student.Todo.Data. Но раз по заданию это не требуется, то оставь так

2023-12-28 16:48 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.Todo.Data/TaskDatabase.cs
> +		public TaskDatabase(string connectionString)
Конструктор обычно располагают вверху, сразу после полей

2023-12-28 16:48 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.WebFormsTodo/TaskManagerState.cs
> +					HttpContext.Current.Session["_userData"] = new TaskDatabase("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=E:\\workge\\student_223024\\BUKEP.Student.WebFormsTodo\\App_Data\\Database1.mdf;
брать строку подключения нужно из web config. Примерно так: ConfigurationManager.ConnectionStrings[ConnectionName].ConnectionString.

2023-12-28 16:48 UTC, DmitryKrekshin commented on student_223024/BUKEP.Student.WebFormsTodo/Web.config
> +    <add name="Database" connectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=E:\workge\student_223024\BUKEP.Student.WebFormsTodo\App_Data\Database1.mdf;Integrated Security=True"></a
Не вижу файлов базы данных. И строка подключения должна выглядеть иначе, должен быть относительный путь к файлу.

2023-12-28 20:14 UTC, SheinEA requested changes

2023-12-28 20:14 UTC, SheinEA commented on student_223024/BUKEP.Student.Todo.Data/TaskDatabase.cs
> +			_dbCon = new(connectionString);
Не правильно создавать и открывать соединение в конструкторе. Мы не знаем какое время будет жить класс и в каком порядке будут вызываться его методы. Мы должны открывать и закрывать соединение при каждом обращении к БД

2023-12-28 20:14 UTC, SheinEA commented on student_223024/BUKEP.Student.Todo.Data/TaskDatabase.cs
> +			SqlCommand sql = new($"SELECT * FROM TaskTable WHERE id = {id}", _dbCon);
Нельзя использовать конкатенации строк в запросах это ведет к уязвимости через sql инъекции

2023-12-28 20:14 UTC, SheinEA commented on student_223024/BUKEP.Student.WebFormsTodo/Web.config
> +    <add name="Database" connectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=E:\workge\student_223024\BUKEP.Student.WebFormsTodo\App_Data\Database1.mdf;Integrated Security=True"></a
Указан физический путь к файлу. Так не подходит, у меня на машине другое расположение проекта

2023-12-28 20:14 UTC, SheinEA commented on student_223024/BUKEP.Student.WebFormsTodo/packages.config
> +  <package id="Microsoft.Identity.Client" version="4.47.2" targetFramework="net48" />
А что это за куча пакетов? Неужели для подключения sql все это нужно?

2023-12-28 20:14 UTC, SheinEA commented on student_223024/BUKEP.Student.WebFormsTodo/TaskManagerState.cs
>  namespace BUKEP.Student.WebFormsTodo
Нам не нужно этот класс ни как менять. Нам вообще не нужно его править, потому что мы должны перестать его использовать просто в своем коде, он нам нужен был для работы с состоянием. Теперь состояние хранится в БД

2023-12-28 20:18 UTC, RodionGromo commented on student_223024/BUKEP.Student.WebFormsTodo/packages.config
> +  <package id="Microsoft.Identity.Client" version="4.47.2" targetFramework="net48" />
Microsoft.Data.SqlClient точно нужен, остальное наверное как зависимости встали, но я попробую убрать лишнее

2024-01-05 15:02 UTC, RodionGromo commented on student_223024/BUKEP.Student.Todo.Data/TaskDatabase.cs
> +		private int _taskIndex = 0;
ну, вообще нет, но я исправил и теперь да

2024-01-05 15:15 UTC, RodionGromo commented
да боже что за ужас как тут откатить действия

2024-01-05 15:22 UTC, RodionGromo commented
эх ладно оставлю так, не знаю как убрать этот мусор теперь

2024-01-07 19:08 UTC, merged